from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages

class PresentationState(TypedDict):
    # Tracks the conversation history and LLM calls
    messages: Annotated[list, add_messages]
    
    # The original user request (e.g., "Make 5 slides for Q1 sales")
    user_prompt: str
    
    # Path to the uploaded CSV file
    csv_file_path: str
    
    # The JSON or text summary generated by the Data Analyst agent
    data_summary: str
    
    # The 5-slide markdown structure planned by the Orchestrator
    outline: str
    
    # The current iteration of the Beamer LaTeX code
    tex_code: str
    
    # The error output from the Tectonic compiler (if it fails)
    error_log: str
    
    # CRITICAL FOR BUDGET: Tracks how many times the Critic loop has run
    revision_count: int
    
    # The path to the final compiled presentation
    final_pdf_path: str
